version: '2.4'

services:
  mongo:
    image: x-lab/mongo:latest
    container_name: rs_mongo
    network_mode: host
    privileged: true

  rabbitmq:
    image: x-lab/rabbitmq:management
    container_name: rs_rabbitmq
    network_mode: host
    privileged: true

  dhcp:
    image: x-lab/isc-dhcp-server:latest
    container_name: rs_dhcp
    network_mode: host
    privileged: true
    volumes:
      - ${VOLUME_DIR}/rackhd/dhcp:/var/lib/dhcp
      - ${VOLUME_DIR}/rackhd/dhcp/config:/etc/dhcp
      - ${VOLUME_DIR}/rackhd/dhcp/defaults:/etc/defaults

  files:
    image: x-lab/rackshift-files:v1.0.0
    container_name: rs_files
    network_mode: host
    privileged: true
    volumes:
      - ${VOLUME_DIR}/rackhd/files/mount:/files

  dhcp-proxy:
    depends_on:
      - dhcp
      - mongo
      - rabbitmq
    image: x-lab/on-dhcp-proxy:v1.0.0
    container_name: rs_dhcp-proxy
    network_mode: host
    privileged: true
    volumes:
      - ${VOLUME_DIR}/rackhd/dhcp:/var/lib/dhcp
      - ${VOLUME_DIR}/rackhd/monorail:/opt/monorail

  http:
    depends_on:
      - files
      - mongo
      - rabbitmq
    image: x-lab/on-http:v1.0.0
    container_name: rs_http
    network_mode: host
    privileged: true
    volumes:
      - ${VOLUME_DIR}/rackhd/files/mount/common:/RackHD/on-http/static/http/common
      - ${VOLUME_DIR}/rackhd/monorail:/opt/monorail

  syslog:
    depends_on:
      - mongo
      - rabbitmq
    image: x-lab/on-syslog:v1.0.0
    container_name: rs_syslog
    network_mode: host
    privileged: true
    volumes:
      - ${VOLUME_DIR}/rackhd/monorail:/opt/monorail

  taskgraph:
    depends_on:
      - dhcp
      - mongo
      - rabbitmq
      - syslog
    image: x-lab/rackshift-taskgraph:v1.0.0
    container_name: rs_taskgraph
    network_mode: host
    privileged: true
    volumes:
      - ${VOLUME_DIR}/rackhd/monorail:/opt/monorail

  tftp:
    depends_on:
      - files
      - mongo
      - rabbitmq
      - syslog
    image: x-lab/on-tftp:v1.0.0
    container_name: rs_tftp
    network_mode: host
    privileged: true
    volumes:
      - ${VOLUME_DIR}/rackhd/files/mount:/RackHD/on-tftp/static/tftp
      - ${VOLUME_DIR}/rackhd/monorail:/opt/monorail

  rackshift:
    image: x-lab/rackshift:${VERSION}
    container_name: rs_core
    privileged: true
    pid: host
    ports:
      - ${HTTP_PORT}:8082
    depends_on:
      - rackshift-plugins
    volumes:
      - ${VOLUME_DIR}:/opt/rackshift
      - ${VOLUME_DIR}/rackhd/files/common:/opt/rackshift/rackhd/files/common
      - /var/run/docker.sock:/var/run/docker.sock

  rackshift-proxy:
    image: x-lab/rackshift-proxy:v1.0.0
    container_name: rs_proxy
    privileged: true
    ports:
      - 8083:8083
    volumes:
      - ${VOLUME_DIR}:/opt/rackshift
      - ${VOLUME_DIR}/rackhd/files/common:/opt/rackshift/rackhd/files/common
      - /var/run/docker.sock:/var/run/docker.sock

  rackshift-plugins:
    image: x-lab/rackshift-plugins:v1.0.0
    container_name: rs_plugins
    volumes:
      - ${VOLUME_DIR}/plugins:/plugins

  ipmitool:
    image: x-lab/ipmitool:latest
    container_name: rs_ipmitool

  racadm:
    image: x-lab/racadm-docker:latest
    container_name: rs_racadm
