# Copyright 2016, EMC, Inc.

version: '2'

services:

  rabbitmq: # 5672, 15672
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rabbitmq:management
    network_mode: host
    privileged: true

  dhcp: # 67/udp
    image: registry.cn-qingdao.aliyuncs.com/x-lab/isc-dhcp-server:latest
    network_mode: host
    privileged: true
    volumes:
      - /opt/rackshift/rackhd/dhcp:/var/lib/dhcp
      - ./rackhd/dhcp/config:/etc/dhcp
      - ./rackhd/dhcp/defaults:/etc/defaults

  files:
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift-files:v1.5.1
    network_mode: host
    privileged: true
    volumes:
      - ./rackhd/files/mount:/files

  dhcp-proxy-new: # 68/udp, 4011
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift-dhcp-proxy:v1.6.0-dev
    network_mode: host
    privileged: true
    volumes:
      - /opt/rackshift/conf:/opt/rackshift/conf

  tftp: # 69/udp
    image: registry.cn-qingdao.aliyuncs.com/x-lab/tftp:v1.6.0
    network_mode: host
    privileged: true
    volumes:
      - ./rackhd/files/mount:/var/tftpboot

  rackshift: # 8082
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift:v1.6.0-dev
    privileged: true
    pid: host
    ports:
      - 80:8082
    depends_on:
      - mysql
      - plugins
    volumes:
      - /opt/rackshift:/opt/rackshift
      - /opt/rackshift/rackhd/files/common:/opt/rackshift/rackhd/files/common
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    image: registry.cn-qingdao.aliyuncs.com/x-lab/mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /opt/rackshift/conf/mysql:/etc/mysql
      - /opt/rackshift/data/mysql:/var/lib/mysql
      - /opt/rackshift/conf/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin

  proxy: # 8083
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift-proxy:v1.0.0
    privileged: true
    ports:
      - 8083:8083
    volumes:
      - /opt/rackshift:/opt/rackshift
      - /opt/rackshift/rackhd/files/common:/opt/rackshift/rackhd/files/common
      - /var/run/docker.sock:/var/run/docker.sock

  plugins:
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift-plugins:v1.5.1
    volumes:
      - /opt/rackshift/plugins:/plugins

