# Copyright 2016, EMC, Inc.

version: '2'

services:

  mongo: # 27017
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/mongo:latest
    network_mode: host
    privileged: true

  rabbitmq: # 5672, 15672
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/rabbitmq:management
    network_mode: host
    privileged: true

  dhcp: # 67/udp
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/isc-dhcp-server:latest
    network_mode: host
    privileged: true
    volumes:
      - /opt/rackshift/rackhd/dhcp:/var/lib/dhcp
      - ./rackhd/dhcp/config:/etc/dhcp
      - ./rackhd/dhcp/defaults:/etc/defaults

  files:
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/rackshift-files:v1.0.0
    network_mode: host
    privileged: true
    volumes:
      - ./rackhd/files/mount:/files

  # RackHD services

  dhcp-proxy: # 68/udp, 4011
    depends_on:
      - dhcp
      - mongo
      - rabbitmq
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/rackhd/on-dhcp-proxy:v1.0.0
    network_mode: host
    privileged: true
    volumes:
      - /opt/rackshift/rackhd/dhcp :/var/lib/dhcp
      - ./rackhd/monorail:/opt/monorail

  http: # 9090, 9080
    depends_on:
      - files
      - mongo
      - rabbitmq
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/on-http:v1.0.0
    network_mode: host
    privileged: true
    volumes:
      - /opt/rackshift/rackhd/files/mount/common:/RackHD/on-http/static/http/common
      - ./rackhd/monorail:/opt/monorail

  syslog: # 514/udp
    depends_on:
      - mongo
      - rabbitmq
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/on-syslog:v1.0.0
    network_mode: host
    privileged: true
    volumes:
      - ./rackhd/monorail:/opt/monorail

  taskgraph:
    depends_on:
      - dhcp
      - mongo
      - rabbitmq
      - syslog
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift-taskgraph:v1.0.0
    network_mode: host
    privileged: true
    volumes:
      - ./rackhd/monorail:/opt/monorail

  tftp: # 69/udp
    depends_on:
      - files
      - mongo
      - rabbitmq
      - syslog
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/on-tftp:v1.0.0
    network_mode: host
    privileged: true
    volumes:
      - ./rackhd/files/mount:/RackHD/on-tftp/static/tftp
      - ./rackhd/monorail:/opt/monorail

  # RackHD services

  rackshift: # 8082
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/rackshift:v1.1.0
    privileged: true
    pid: host
    ports:
      - 80:8082
    depends_on:
      - mysql
      - rackshift-plugins
    volumes:
      - /opt/rackshift:/opt/rackshift
      - /opt/rackshift/rackhd/files/common:/opt/rackshift/rackhd/files/common
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /opt/rackshift/conf/mysql:/etc/mysql
      - /opt/rackshift/data/mysql:/var/lib/mysql
      - /opt/rackshift/conf/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin

  rackshift-proxy: # 8083
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/rackshift-proxy:v1.0.0
    privileged: true
    ports:
      - 8083:8083
    volumes:
      - /opt/rackshift:/opt/rackshift
      - /opt/rackshift/rackhd/files/common:/opt/rackshift/rackhd/files/common
      - /var/run/docker.sock:/var/run/docker.sock

  rackshift-plugins:
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/rackshift-plugins:v1.0.0
    volumes:
      - /opt/rackshift/plugins:/plugins

  ipmitool:
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/kfox1111/ipmitool:latest

  racadm:
    image: registry.cn-qingdao.aliyuncs.com/x-lab/rackshift/kciepluc/racadm-docker:latest

